/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as GuestIkmRouteImport } from './routes/guest/ikm'
import { Route as AdminTamuRouteImport } from './routes/admin/tamu'
import { Route as AdminSlidersRouteImport } from './routes/admin/sliders'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminLayananRouteImport } from './routes/admin/layanan'
import { Route as GuestSurveyIndexRouteImport } from './routes/guest/survey.index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminSurveyIndexRouteImport } from './routes/admin/survey/index'
import { Route as AdminFormsIndexRouteImport } from './routes/admin/forms/index'
import { Route as GuestSurveyFormIdRouteImport } from './routes/guest/survey.$formId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users/$userId'
import { Route as AdminSurveySurveyIdRouteImport } from './routes/admin/survey/$surveyId'
import { Route as AdminReportsBukuTamuRouteImport } from './routes/admin/reports/buku-tamu'
import { Route as AdminFormsFormIdQuestionsRouteImport } from './routes/admin/forms/$formId.questions'
import { Route as AdminFormsFormIdQuestionsIndexRouteImport } from './routes/admin/forms/$formId.questions.index'
import { Route as AdminFormsFormIdQuestionsQuestionIdChoicesRouteImport } from './routes/admin/forms/$formId.questions.$questionId.choices'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const GuestIkmRoute = GuestIkmRouteImport.update({
  id: '/guest/ikm',
  path: '/guest/ikm',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTamuRoute = AdminTamuRouteImport.update({
  id: '/tamu',
  path: '/tamu',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSlidersRoute = AdminSlidersRouteImport.update({
  id: '/sliders',
  path: '/sliders',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLayananRoute = AdminLayananRouteImport.update({
  id: '/layanan',
  path: '/layanan',
  getParentRoute: () => AdminRouteRoute,
} as any)
const GuestSurveyIndexRoute = GuestSurveyIndexRouteImport.update({
  id: '/guest/survey/',
  path: '/guest/survey/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSurveyIndexRoute = AdminSurveyIndexRouteImport.update({
  id: '/survey/',
  path: '/survey/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFormsIndexRoute = AdminFormsIndexRouteImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const GuestSurveyFormIdRoute = GuestSurveyFormIdRouteImport.update({
  id: '/guest/survey/$formId',
  path: '/guest/survey/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSurveySurveyIdRoute = AdminSurveySurveyIdRouteImport.update({
  id: '/survey/$surveyId',
  path: '/survey/$surveyId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsBukuTamuRoute = AdminReportsBukuTamuRouteImport.update({
  id: '/reports/buku-tamu',
  path: '/reports/buku-tamu',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFormsFormIdQuestionsRoute =
  AdminFormsFormIdQuestionsRouteImport.update({
    id: '/forms/$formId/questions',
    path: '/forms/$formId/questions',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminFormsFormIdQuestionsIndexRoute =
  AdminFormsFormIdQuestionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminFormsFormIdQuestionsRoute,
  } as any)
const AdminFormsFormIdQuestionsQuestionIdChoicesRoute =
  AdminFormsFormIdQuestionsQuestionIdChoicesRouteImport.update({
    id: '/$questionId/choices',
    path: '/$questionId/choices',
    getParentRoute: () => AdminFormsFormIdQuestionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/layanan': typeof AdminLayananRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sliders': typeof AdminSlidersRoute
  '/admin/tamu': typeof AdminTamuRoute
  '/guest/ikm': typeof GuestIkmRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/reports/buku-tamu': typeof AdminReportsBukuTamuRoute
  '/admin/survey/$surveyId': typeof AdminSurveySurveyIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/guest/survey/$formId': typeof GuestSurveyFormIdRoute
  '/admin/forms/': typeof AdminFormsIndexRoute
  '/admin/survey/': typeof AdminSurveyIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/guest/survey/': typeof GuestSurveyIndexRoute
  '/admin/forms/$formId/questions': typeof AdminFormsFormIdQuestionsRouteWithChildren
  '/admin/forms/$formId/questions/': typeof AdminFormsFormIdQuestionsIndexRoute
  '/admin/forms/$formId/questions/$questionId/choices': typeof AdminFormsFormIdQuestionsQuestionIdChoicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/layanan': typeof AdminLayananRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sliders': typeof AdminSlidersRoute
  '/admin/tamu': typeof AdminTamuRoute
  '/guest/ikm': typeof GuestIkmRoute
  '/admin': typeof AdminIndexRoute
  '/admin/reports/buku-tamu': typeof AdminReportsBukuTamuRoute
  '/admin/survey/$surveyId': typeof AdminSurveySurveyIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/guest/survey/$formId': typeof GuestSurveyFormIdRoute
  '/admin/forms': typeof AdminFormsIndexRoute
  '/admin/survey': typeof AdminSurveyIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/guest/survey': typeof GuestSurveyIndexRoute
  '/admin/forms/$formId/questions': typeof AdminFormsFormIdQuestionsIndexRoute
  '/admin/forms/$formId/questions/$questionId/choices': typeof AdminFormsFormIdQuestionsQuestionIdChoicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/layanan': typeof AdminLayananRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sliders': typeof AdminSlidersRoute
  '/admin/tamu': typeof AdminTamuRoute
  '/guest/ikm': typeof GuestIkmRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/reports/buku-tamu': typeof AdminReportsBukuTamuRoute
  '/admin/survey/$surveyId': typeof AdminSurveySurveyIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/guest/survey/$formId': typeof GuestSurveyFormIdRoute
  '/admin/forms/': typeof AdminFormsIndexRoute
  '/admin/survey/': typeof AdminSurveyIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/guest/survey/': typeof GuestSurveyIndexRoute
  '/admin/forms/$formId/questions': typeof AdminFormsFormIdQuestionsRouteWithChildren
  '/admin/forms/$formId/questions/': typeof AdminFormsFormIdQuestionsIndexRoute
  '/admin/forms/$formId/questions/$questionId/choices': typeof AdminFormsFormIdQuestionsQuestionIdChoicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/sitemap.xml'
    | '/admin/layanan'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/sliders'
    | '/admin/tamu'
    | '/guest/ikm'
    | '/admin/'
    | '/admin/reports/buku-tamu'
    | '/admin/survey/$surveyId'
    | '/admin/users/$userId'
    | '/api/auth/$'
    | '/guest/survey/$formId'
    | '/admin/forms/'
    | '/admin/survey/'
    | '/admin/users/'
    | '/guest/survey/'
    | '/admin/forms/$formId/questions'
    | '/admin/forms/$formId/questions/'
    | '/admin/forms/$formId/questions/$questionId/choices'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/admin/layanan'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/sliders'
    | '/admin/tamu'
    | '/guest/ikm'
    | '/admin'
    | '/admin/reports/buku-tamu'
    | '/admin/survey/$surveyId'
    | '/admin/users/$userId'
    | '/api/auth/$'
    | '/guest/survey/$formId'
    | '/admin/forms'
    | '/admin/survey'
    | '/admin/users'
    | '/guest/survey'
    | '/admin/forms/$formId/questions'
    | '/admin/forms/$formId/questions/$questionId/choices'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/sitemap.xml'
    | '/admin/layanan'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/sliders'
    | '/admin/tamu'
    | '/guest/ikm'
    | '/admin/'
    | '/admin/reports/buku-tamu'
    | '/admin/survey/$surveyId'
    | '/admin/users/$userId'
    | '/api/auth/$'
    | '/guest/survey/$formId'
    | '/admin/forms/'
    | '/admin/survey/'
    | '/admin/users/'
    | '/guest/survey/'
    | '/admin/forms/$formId/questions'
    | '/admin/forms/$formId/questions/'
    | '/admin/forms/$formId/questions/$questionId/choices'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  GuestIkmRoute: typeof GuestIkmRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  GuestSurveyFormIdRoute: typeof GuestSurveyFormIdRoute
  GuestSurveyIndexRoute: typeof GuestSurveyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/guest/ikm': {
      id: '/guest/ikm'
      path: '/guest/ikm'
      fullPath: '/guest/ikm'
      preLoaderRoute: typeof GuestIkmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tamu': {
      id: '/admin/tamu'
      path: '/tamu'
      fullPath: '/admin/tamu'
      preLoaderRoute: typeof AdminTamuRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/sliders': {
      id: '/admin/sliders'
      path: '/sliders'
      fullPath: '/admin/sliders'
      preLoaderRoute: typeof AdminSlidersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/layanan': {
      id: '/admin/layanan'
      path: '/layanan'
      fullPath: '/admin/layanan'
      preLoaderRoute: typeof AdminLayananRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/guest/survey/': {
      id: '/guest/survey/'
      path: '/guest/survey'
      fullPath: '/guest/survey/'
      preLoaderRoute: typeof GuestSurveyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/survey/': {
      id: '/admin/survey/'
      path: '/survey'
      fullPath: '/admin/survey/'
      preLoaderRoute: typeof AdminSurveyIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/forms/': {
      id: '/admin/forms/'
      path: '/forms'
      fullPath: '/admin/forms/'
      preLoaderRoute: typeof AdminFormsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/guest/survey/$formId': {
      id: '/guest/survey/$formId'
      path: '/guest/survey/$formId'
      fullPath: '/guest/survey/$formId'
      preLoaderRoute: typeof GuestSurveyFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/survey/$surveyId': {
      id: '/admin/survey/$surveyId'
      path: '/survey/$surveyId'
      fullPath: '/admin/survey/$surveyId'
      preLoaderRoute: typeof AdminSurveySurveyIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports/buku-tamu': {
      id: '/admin/reports/buku-tamu'
      path: '/reports/buku-tamu'
      fullPath: '/admin/reports/buku-tamu'
      preLoaderRoute: typeof AdminReportsBukuTamuRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/forms/$formId/questions': {
      id: '/admin/forms/$formId/questions'
      path: '/forms/$formId/questions'
      fullPath: '/admin/forms/$formId/questions'
      preLoaderRoute: typeof AdminFormsFormIdQuestionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/forms/$formId/questions/': {
      id: '/admin/forms/$formId/questions/'
      path: '/'
      fullPath: '/admin/forms/$formId/questions/'
      preLoaderRoute: typeof AdminFormsFormIdQuestionsIndexRouteImport
      parentRoute: typeof AdminFormsFormIdQuestionsRoute
    }
    '/admin/forms/$formId/questions/$questionId/choices': {
      id: '/admin/forms/$formId/questions/$questionId/choices'
      path: '/$questionId/choices'
      fullPath: '/admin/forms/$formId/questions/$questionId/choices'
      preLoaderRoute: typeof AdminFormsFormIdQuestionsQuestionIdChoicesRouteImport
      parentRoute: typeof AdminFormsFormIdQuestionsRoute
    }
  }
}

interface AdminFormsFormIdQuestionsRouteChildren {
  AdminFormsFormIdQuestionsIndexRoute: typeof AdminFormsFormIdQuestionsIndexRoute
  AdminFormsFormIdQuestionsQuestionIdChoicesRoute: typeof AdminFormsFormIdQuestionsQuestionIdChoicesRoute
}

const AdminFormsFormIdQuestionsRouteChildren: AdminFormsFormIdQuestionsRouteChildren =
  {
    AdminFormsFormIdQuestionsIndexRoute: AdminFormsFormIdQuestionsIndexRoute,
    AdminFormsFormIdQuestionsQuestionIdChoicesRoute:
      AdminFormsFormIdQuestionsQuestionIdChoicesRoute,
  }

const AdminFormsFormIdQuestionsRouteWithChildren =
  AdminFormsFormIdQuestionsRoute._addFileChildren(
    AdminFormsFormIdQuestionsRouteChildren,
  )

interface AdminRouteRouteChildren {
  AdminLayananRoute: typeof AdminLayananRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSlidersRoute: typeof AdminSlidersRoute
  AdminTamuRoute: typeof AdminTamuRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminReportsBukuTamuRoute: typeof AdminReportsBukuTamuRoute
  AdminSurveySurveyIdRoute: typeof AdminSurveySurveyIdRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminFormsIndexRoute: typeof AdminFormsIndexRoute
  AdminSurveyIndexRoute: typeof AdminSurveyIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminFormsFormIdQuestionsRoute: typeof AdminFormsFormIdQuestionsRouteWithChildren
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminLayananRoute: AdminLayananRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSlidersRoute: AdminSlidersRoute,
  AdminTamuRoute: AdminTamuRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminReportsBukuTamuRoute: AdminReportsBukuTamuRoute,
  AdminSurveySurveyIdRoute: AdminSurveySurveyIdRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminFormsIndexRoute: AdminFormsIndexRoute,
  AdminSurveyIndexRoute: AdminSurveyIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminFormsFormIdQuestionsRoute: AdminFormsFormIdQuestionsRouteWithChildren,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  GuestIkmRoute: GuestIkmRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  GuestSurveyFormIdRoute: GuestSurveyFormIdRoute,
  GuestSurveyIndexRoute: GuestSurveyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
